// <auto-generated />
namespace VoteSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AnswerTable_CaseType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AnswerTable_CaseType));
        
        string IMigrationMetadata.Id
        {
            get { return "202101181140160_AnswerTable_CaseType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
